### ISSUE TITLE
Psi and Level Up! Reloaded

### ISSUE THREAD

**Issue by iamsolarflare** [EmosewaPixel/The-Pixel-Community-Pack#3]
While normally I'm more one to suggest dimensional mods, I kind of get the feeling that this generally isn't the type of thing you're looking for?

That said, Psi is a really cool magitek mod, and since PlusTIC adds materials for it, it kind of fits into the whole atmosphere?

Level Up! is more a wild suggestion because I'm a sucker for incremental systems like that which give you benefits at the cost of your ingame exp.

**Comment by EmosewaPixel** [comment]
The thing with Psi is that it's kind of OP to a point and there's not really a way to gate it besides for gating the mod as a whole. Level Up!, since we have a Tinker's in the pack would be kind of pointless to have. I haven't yet decided if this is going to be a skyblock or not, so you can suggest dimension mods.
